### ISSUE TITLE
Question: From Bert to Onnx?

### ISSUE THREAD

**Issue by dgerding** [DomHudson/bert-in-production#1]
I appreciate this collection and I just wondered if it made sense to you if the collection would be a quick path to getting either a Bert or an Elmo model out as an onnx model that I could then use with ml.net?

Thanks again

**Comment by DomHudson** [comment]
Hi, thanks for your interest in my repository!

I recommend [Microsoft's onnxruntime](https://github.com/microsoft/onnxruntime). This notebook shows a route to convert a huggingface BERT model to a serialized onnx model. https://github.com/huggingface/transformers/blob/master/notebooks/04-onnx-export.ipynb

Hope this helps,
Dom
